// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnmjwnvvhcxfasrxbdxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBubWp3bnZ2aGN4ZmFzcnhiZHhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1OTk3NjksImV4cCI6MjA2OTE3NTc2OX0.5SvwnJGFY-8H6iWImLPUPqoNqlVHaxjkQdjK_JCwDjY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});